# Generated by Django 5.2.1 on 2025-05-26 22:27

import Apps.participant.Enums.statusEnum
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hacker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('HACKER', 'Hacker'), ('MENTOR', 'Mentor'), ('VOLUNTEER', 'Volunteer'), ('SPONSOR', 'Sponsor'), ('ADMIN', 'Admin')])),
                ('accepted_terms_and_conditions', models.BooleanField(default=False)),
                ('t_shirt_size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')])),
                ('origin', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('CANCELLED', 'Cancelled'), ('INVITED', 'Invited'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('ATTENDED', 'Attended'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted')], default=Apps.participant.Enums.statusEnum.StatusEnum['UNDER_REVIEW'])),
                ('university', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('graduation_year', models.IntegerField()),
                ('under_age', models.BooleanField()),
                ('lenny_face', models.CharField(max_length=255)),
                ('hear_about_us', models.CharField(max_length=255)),
                ('why_excited', models.TextField()),
                ('first_hackathon', models.BooleanField()),
                ('personal_projects', models.TextField()),
                ('github', models.URLField(blank=True, null=True)),
                ('devpost', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('personal', models.URLField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/hacker/')),
                ('share_cv', models.BooleanField()),
                ('subscribe', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('HACKER', 'Hacker'), ('MENTOR', 'Mentor'), ('VOLUNTEER', 'Volunteer'), ('SPONSOR', 'Sponsor'), ('ADMIN', 'Admin')])),
                ('accepted_terms_and_conditions', models.BooleanField(default=False)),
                ('t_shirt_size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')])),
                ('origin', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('CANCELLED', 'Cancelled'), ('INVITED', 'Invited'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('ATTENDED', 'Attended'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted')], default=Apps.participant.Enums.statusEnum.StatusEnum['UNDER_REVIEW'])),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('english_level', models.IntegerField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('ADVANCED', 'Advanced'), ('NATIVE', 'Native')])),
                ('hear_about_us', models.CharField(max_length=255)),
                ('personal_projects', models.TextField()),
                ('github', models.URLField(blank=True, null=True)),
                ('devpost', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('personal', models.URLField(blank=True, null=True)),
                ('first_hackathon', models.BooleanField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/mentor/')),
                ('subscribe', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('HACKER', 'Hacker'), ('MENTOR', 'Mentor'), ('VOLUNTEER', 'Volunteer'), ('SPONSOR', 'Sponsor'), ('ADMIN', 'Admin')])),
                ('accepted_terms_and_conditions', models.BooleanField(default=False)),
                ('t_shirt_size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')])),
                ('origin', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('CANCELLED', 'Cancelled'), ('INVITED', 'Invited'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('ATTENDED', 'Attended'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted')], default=Apps.participant.Enums.statusEnum.StatusEnum['UNDER_REVIEW'])),
                ('company_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('HACKER', 'Hacker'), ('MENTOR', 'Mentor'), ('VOLUNTEER', 'Volunteer'), ('SPONSOR', 'Sponsor'), ('ADMIN', 'Admin')])),
                ('accepted_terms_and_conditions', models.BooleanField(default=False)),
                ('t_shirt_size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')])),
                ('origin', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('CANCELLED', 'Cancelled'), ('INVITED', 'Invited'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('ATTENDED', 'Attended'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted')], default=Apps.participant.Enums.statusEnum.StatusEnum['UNDER_REVIEW'])),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('degree', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('languages', models.CharField(max_length=255)),
                ('first_volunteering', models.BooleanField()),
                ('hear_about_us', models.CharField(max_length=255)),
                ('cool_skill', models.CharField()),
                ('personal_qualities', models.CharField()),
                ('personal_weakness', models.CharField()),
                ('motivation', models.TextField()),
                ('nigth_shifts', models.BooleanField()),
                ('subscribe', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('HACKER', 'Hacker'), ('MENTOR', 'Mentor'), ('VOLUNTEER', 'Volunteer'), ('SPONSOR', 'Sponsor'), ('ADMIN', 'Admin')])),
                ('accepted_terms_and_conditions', models.BooleanField(default=False)),
                ('t_shirt_size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')])),
                ('origin', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('CANCELLED', 'Cancelled'), ('INVITED', 'Invited'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('ATTENDED', 'Attended'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted')], default=Apps.participant.Enums.statusEnum.StatusEnum['UNDER_REVIEW'])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
