# Generated by Django 5.2.1 on 2025-06-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='status',
            field=models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('CANCELLED', 'Cancelled'), ('INVITED', 'Invited'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('ATTENDED', 'Attended'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted')], default='Under Review'),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='status',
            field=models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('CANCELLED', 'Cancelled'), ('INVITED', 'Invited'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('ATTENDED', 'Attended'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted')], default='Under Review'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='english_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('ADVANCED', 'Advanced'), ('NATIVE', 'Native')]),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='status',
            field=models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('CANCELLED', 'Cancelled'), ('INVITED', 'Invited'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('ATTENDED', 'Attended'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted')], default='Under Review'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('CANCELLED', 'Cancelled'), ('INVITED', 'Invited'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('ATTENDED', 'Attended'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted')], default='Under Review'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('CANCELLED', 'Cancelled'), ('INVITED', 'Invited'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('ATTENDED', 'Attended'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted')], default='Under Review'),
        ),
    ]
