# Generated by Django 5.2.1 on 2025-06-01 18:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('participant', '0003_alter_admin_status_alter_hacker_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('NORMALACTIVITY', 'Normal Activity'), ('WORKSHOP', 'Workshop'), ('MEAL', 'Meal')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('admin_particpants', models.ManyToManyField(related_name='activities', to='participant.admin')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('hacker_particpants', models.ManyToManyField(related_name='activities', to='participant.hacker')),
                ('mentor_particpants', models.ManyToManyField(related_name='activities', to='participant.mentor')),
                ('sponsor_particpants', models.ManyToManyField(related_name='activities', to='participant.sponsor')),
                ('volunteer_particpants', models.ManyToManyField(related_name='activities', to='participant.volunteer')),
            ],
        ),
    ]
