# Generated by Django 5.2.1 on 2025-06-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='admin_particpants',
            new_name='admin_participants',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='hacker_particpants',
            new_name='hacker_participants',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='mentor_particpants',
            new_name='mentor_participants',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='sponsor_particpants',
            new_name='sponsor_participants',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='volunteer_particpants',
            new_name='volunteer_participants',
        ),
    ]
