services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Madrid
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: Mybits2DB

  web:
    build: .
    ports:
      - "0.0.0.0:8080:8080"
    command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 --workers 3 Mybits2.wsgi:application"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      DB_HOST: ${HOST}
      DB_PORT: ${PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Madrid
    container_name: Mybits2
    volumes:
    - ./media:/Mybits2/media

  test:
    build: .
    command: bash -c "python manage.py migrate && coverage run -m pytest && mkdir -p /Mybits2/coverage_reports && coverage report > /Mybits2/coverage_reports/coverage.txt && coverage html -d /Mybits2/coverage_reports/html"
    depends_on:
      - web
    environment:
      DB_HOST: ${HOST}
      DB_PORT: ${PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Madrid
    container_name: Mybits2Test
    volumes:
      - ./coverage_reports:/Mybits2/coverage_reports

volumes:
  postgres_data: