# Generated by Django 4.2.20 on 2025-05-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('AppName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('timezone', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('hacker_deadline', models.DateTimeField()),
                ('mentor_deadline', models.DateTimeField()),
                ('volunteer_deadline', models.DateTimeField()),
                ('sponsor_deadline', models.DateTimeField()),
                ('domain_link', models.URLField(null=True)),
                ('live_link', models.URLField(null=True)),
                ('x_link', models.URLField(null=True)),
                ('facebook_link', models.URLField(null=True)),
                ('instagram_link', models.URLField(null=True)),
                ('terms_and_conditions_link', models.CharField(max_length=255)),
                ('activities_enabled', models.BooleanField(default=False)),
                ('warehouse_enabled', models.BooleanField(default=False)),
                ('hardware_enabled', models.BooleanField(default=False)),
                ('judging_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
