# Generated by Django 5.2.1 on 2025-05-26 22:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('AppName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('timezone', models.CharField(choices=[('UTC_MINUS_12', 'GMT+12'), ('UTC_MINUS_11', 'GMT+11'), ('UTC_MINUS_10', 'GMT+10'), ('UTC_MINUS_9_30', 'GMT+9:30'), ('UTC_MINUS_9', 'GMT+9'), ('UTC_MINUS_8', 'GMT+8'), ('UTC_MINUS_7', 'GMT+7'), ('UTC_MINUS_6', 'GMT+6'), ('UTC_MINUS_5', 'GMT+5'), ('UTC_MINUS_4', 'GMT+4'), ('UTC_MINUS_3_30', 'GMT+3:30'), ('UTC_MINUS_3', 'GMT+3'), ('UTC_MINUS_2', 'GMT+2'), ('UTC_MINUS_1', 'GMT+1'), ('UTC', 'GMT+0'), ('UTC_PLUS_1', 'GMT-1'), ('UTC_PLUS_2', 'GMT-2'), ('UTC_PLUS_3', 'GMT-3'), ('UTC_PLUS_3_30', 'GMT-3:30'), ('UTC_PLUS_4', 'GMT-4'), ('UTC_PLUS_4_30', 'GMT-4:30'), ('UTC_PLUS_5', 'GMT-5'), ('UTC_PLUS_5_30', 'GMT-5:30'), ('UTC_PLUS_5_45', 'GMT-5:45'), ('UTC_PLUS_6', 'GMT-6'), ('UTC_PLUS_6_30', 'GMT-6:30'), ('UTC_PLUS_7', 'GMT-7'), ('UTC_PLUS_8', 'GMT-8'), ('UTC_PLUS_8_30', 'GMT-8:30'), ('UTC_PLUS_8_45', 'GMT-8:45'), ('UTC_PLUS_9', 'GMT-9'), ('UTC_PLUS_9_30', 'GMT-9:30'), ('UTC_PLUS_10', 'GMT-10'), ('UTC_PLUS_10_30', 'GMT-10:30'), ('UTC_PLUS_11', 'GMT-11'), ('UTC_PLUS_11_30', 'GMT-11:30'), ('UTC_PLUS_12', 'GMT-12'), ('UTC_PLUS_12_45', 'GMT-12:45'), ('UTC_PLUS_13', 'GMT-13'), ('UTC_PLUS_14', 'GMT-14')], max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('hacker_deadline', models.DateTimeField()),
                ('mentor_deadline', models.DateTimeField()),
                ('volunteer_deadline', models.DateTimeField()),
                ('sponsor_deadline', models.DateTimeField()),
                ('domain_link', models.URLField(blank=True, null=True)),
                ('live_link', models.URLField(blank=True, null=True)),
                ('x_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('terms_and_conditions_link', models.CharField(max_length=255)),
                ('activities_enabled', models.BooleanField(default=False)),
                ('warehouse_enabled', models.BooleanField(default=False)),
                ('hardware_enabled', models.BooleanField(default=False)),
                ('judging_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
