# Generated by Django 4.2.20 on 2025-05-13 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='domain_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='live_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='timezone',
            field=models.CharField(choices=[('UTC_MINUS_12', 'GMT+12'), ('UTC_MINUS_11', 'GMT+11'), ('UTC_MINUS_10', 'GMT+10'), ('UTC_MINUS_9_30', 'GMT+9:30'), ('UTC_MINUS_9', 'GMT+9'), ('UTC_MINUS_8', 'GMT+8'), ('UTC_MINUS_7', 'GMT+7'), ('UTC_MINUS_6', 'GMT+6'), ('UTC_MINUS_5', 'GMT+5'), ('UTC_MINUS_4', 'GMT+4'), ('UTC_MINUS_3_30', 'GMT+3:30'), ('UTC_MINUS_3', 'GMT+3'), ('UTC_MINUS_2', 'GMT+2'), ('UTC_MINUS_1', 'GMT+1'), ('UTC', 'GMT+0'), ('UTC_PLUS_1', 'GMT-1'), ('UTC_PLUS_2', 'GMT-2'), ('UTC_PLUS_3', 'GMT-3'), ('UTC_PLUS_3_30', 'GMT-3:30'), ('UTC_PLUS_4', 'GMT-4'), ('UTC_PLUS_4_30', 'GMT-4:30'), ('UTC_PLUS_5', 'GMT-5'), ('UTC_PLUS_5_30', 'GMT-5:30'), ('UTC_PLUS_5_45', 'GMT-5:45'), ('UTC_PLUS_6', 'GMT-6'), ('UTC_PLUS_6_30', 'GMT-6:30'), ('UTC_PLUS_7', 'GMT-7'), ('UTC_PLUS_8', 'GMT-8'), ('UTC_PLUS_8_30', 'GMT-8:30'), ('UTC_PLUS_8_45', 'GMT-8:45'), ('UTC_PLUS_9', 'GMT-9'), ('UTC_PLUS_9_30', 'GMT-9:30'), ('UTC_PLUS_10', 'GMT-10'), ('UTC_PLUS_10_30', 'GMT-10:30'), ('UTC_PLUS_11', 'GMT-11'), ('UTC_PLUS_11_30', 'GMT-11:30'), ('UTC_PLUS_12', 'GMT-12'), ('UTC_PLUS_12_45', 'GMT-12:45'), ('UTC_PLUS_13', 'GMT-13'), ('UTC_PLUS_14', 'GMT-14')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='x_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
