# Generated by Django 5.2.1 on 2025-06-09 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('participant', '0003_alter_admin_status_alter_hacker_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Luggage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('row_position', models.IntegerField()),
                ('column_position', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='luggage_images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.hacker')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rows', models.IntegerField()),
                ('columns', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('luggage', models.ManyToManyField(related_name='warehouse', to='warehouse.luggage')),
            ],
        ),
    ]
