# Generated by Django 4.2.20 on 2025-04-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='prounoun',
            new_name='pronoun',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dietary',
            field=models.CharField(choices=[('NONE', 'None'), ('GLUTEN_FREE', 'Gluten Free'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('HALAL', 'Halal'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
