# Generated by Django 5.2.1 on 2025-06-09 16:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participant', '0003_alter_admin_status_alter_hacker_status_and_more'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('github_link', models.URLField()),
                ('devpost_link', models.URLField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='team.team')),
            ],
        ),
        migrations.CreateModel(
            name='Valoration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valorations', to='participant.admin')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='project.project')),
            ],
        ),
    ]
