# Generated by Django 4.2.20 on 2025-06-08 18:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participant', '0003_alter_admin_status_alter_hacker_status_and_more'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('abreviation', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hardware_images/')),
                ('borrowers', models.ManyToManyField(related_name='borrowed_hardware_items', to='participant.hacker')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
